// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {


    var overlay, tiles;
    if ($('body').is('.index') && device.landscape() === true && $(window).height() < 1500) {
      $('.containerFullBig.top').css('min-height', $(window).height());
    }

    $('.topMenu a').on('click', function(e) {
      var link;
      e.preventDefault();
      link = $(this).attr('href').split('#')[1];
      return $(window).scrollTo($('a[name=' + link + ']').offset().top - 100, 800);
    });

    $('span.next, span.prev').hide();
    $('#my_slider').muslider({
      'responsive': false,
      'animation_duration': 800,
      'width': 1140,
      'height': 855
    });

    overlay = {
      show: function(div, li) {
        var bigWindow, overlayBlock, top;
        overlayBlock = $('#overlay');
        overlayBlock.fadeIn(300);
        top = overlayBlock.height() / 2 - ($(div).height() / 2) - 20;
        if (top < 10) {
          top = 10;
        }
        $(div).css({
          marginTop: top,
          marginLeft: overlayBlock.width() / 2 - ($(div).width() / 2) - 50,
          maxHeight: $(window).height() - 100
        }).show();
        if (div === '.bigWindow') {
          bigWindow = $(div);
          bigWindow.find('h1, h2, p, a').text('').end()
              .find('h1').text(li.find('.caption').text()).end()
              .find('p').html(li.find('.bigCaption p').html()).end()
              .find('img').attr('src', li.data('image'));
        }
      },
      hide: function() {
        var overlayBlock;
        overlayBlock = $('#overlay');
        return overlayBlock.fadeOut(300).children().hide();
      }
    };

    $('#callbackTop, #callbackTop2, .callbackBottom, .questions .button, .ctaTop .button, .packetPrice .button ').on('click', function(e) {
      var label;
      e.preventDefault();
      overlay.show('.window');
      if ($(this).is('.customCMS')) {
        label = $(this).parents('.packet').find('input:checked').siblings('label').text();
        $('.window').find('.nameCMS').val(label).end().find('.priceCMS').val($(this).parents('.packet').find('input:checked').siblings('p').text());
        $('.choosenCMS').show();
      } else {
        $('.choosenCMS').hide();
      }
      if ($(this).is('.label')) {
        return $('.window h2').text('Введите емайл чтобы получить бриф');
      } else {
        return $('.window h2').text('');
      }
    });

    $('.label').on('click', function(e) {
      e.preventDefault();
      overlay.show('.breef');
      $('body').css('overflow', 'hidden');
      $('.breef').find('.nameCMS').val($(this).parents('.packet').find('input:checked').siblings('label').text()).find('.priceCMS').text($(this).parents('.packet').find('input:checked').siblings('p').text());
    });

    $('.close').on('click', function() {
      overlay.hide();
      return $('body').css('overflow', 'auto');
    });

    $('#imgToDown').on('click', function(e) {
      return $(window).scrollTo(750, 300);
    });

    $('.CMSPrice').on('click', function(e) {
      e.preventDefault();
      $('.selectCMS').slideToggle();
      return $(this).toggleClass('opened');
    });

    tiles = $('.tiles');
    tiles.find('li').hover((function() {
      var li;
      li = $(this);
      return li.find('.caption').animate({
        bottom: -95
      }, 200, function() {
        return li.find('.bigCaption').fadeIn(200);
      });
    }), function() {
      var li;
      li = $(this);
      return li.find('.bigCaption').fadeOut(200, function() {
        return li.find('.caption').animate({
          bottom: 0
        }, 200);
      });
    }).click(function(e) {
      e.preventDefault();
      return overlay.show('.bigWindow', $(this));
    });
    $(window).on('scroll', function() {
      if ($(this).scrollTop() > 88) {
        return $('.fixedTop').slideDown();
      } else {
        return $('.fixedTop').slideUp();
      }
    });

      $('.tiles ul li').each(function(){
          var imgurl = ($(this).data('image')).replace('.png', '-min-min.png');
          $(this).css('background-image', 'url('+ imgurl + ')');
      })

    $('#overlay .button, #breefPage .button').on('click', function() {
        var data;
        var form;
        var button = $(this);
      if(button.siblings().is('form')){
          form = button.siblings('form');
      } else {
          form = button.parents('form');
      }

      data = form.serialize();
        console.log(data);
      return $.ajax({
        url: 'mysql.php',
        type: 'POST',
        data: data,
        success: function(result) {
          if ((result*1) > 0 || result === 'ok') {
            if (result !== 'ok') {
              data += '&id=' + result;
            }
            $.ajax({
              url: 'send.php',
              type: 'POST',
              cache: false,
              data: data
            });

              if(button.is('#refferal')){
                  $.alert({
                  title: 'Спасибо!',
                      content: 'Реферальная ссылка будет отправлена вам на почту',
                  });
              } else {
                  $.alert({
                      title: 'Спасибо!',
                      content: 'Мы свяжемся в Вами в ближайшее время!',
                      confirm: function(){
                          if(!button.is('#consult, #refferal')){
                              var nameCMS = (form.find('.nameCMS').val());
                              var priceCMS = (form.find('.priceCMS').val()).split(' ')[0];

                              if (priceCMS > 0){
                                  location.href = 'pay2.php?name='+nameCMS+'&summ='+priceCMS+'&id='+result;
                              } else {
                                  location.href = 'pay.php?id='+result;
                              }
                          }
                      }
                  });

              }
              overlay.hide();

          } else {
            return $.alert({
              title: 'Не удается записать данные.',
              content: 'Проверьте корректность введенных данных'
            });
          }
        },
        failure: function() {
          return $.alert({
            title: 'Не удается записать данные!',
            content: 'Проверьте корректность введенных данных'
          });
        }
      });
    });

    $('.packet li').each(function(){
        if($(this).hasClass('tooltip')){
            $(this).append('<span title="'+$(this).data('title')+'"><i class="fa fa-question-circle"></i></span>')
        }
    })

      $('.blue .tooltip span').tooltipster({
          theme: 'tooltipster-blue',
          contentAsHTML: true
      });

      $('.red .tooltip span').tooltipster({
          theme: 'tooltipster-red',
          contentAsHTML: true
      });

      $('.violet .tooltip span').tooltipster({
          theme: 'tooltipster-violet',
          contentAsHTML: true
      });

  });

}).call(this);

//# sourceMappingURL=common.js.map
